### ISSUE TITLE
Add support for 'triton datacenter get' to node-triton.

### ISSUE THREAD

**Issue by YangYong3** [TritonDataCenter/node-triton#186]
Add support for 'triton datacenter get' to node-triton.

https://apidocs.joyent.com/cloudapi/#GetDatacenter

**Comment by YangYong3** [comment]
https://cr.joyent.us/#/c/1621/

**Comment by jclulow** [comment]
Have you seen `triton datacenters`?  For example:

```
$ triton datacenters 
NAME       URL
eu-ams-1   https://eu-ams-1.api.joyentcloud.com
us-east-1  https://us-east-1.api.joyentcloud.com
us-east-2  https://us-east-2.api.joyentcloud.com
us-east-3  https://us-east-3.api.joyentcloud.com
us-sw-1    https://us-sw-1.api.joyentcloud.com
us-west-1  https://us-west-1.api.joyentcloud.com
```

I'm not completely clear on what new functionality `triton datacenter get` would provide.

**Comment by bahamat** [comment]
Considering that [GetDataenter](https://apidocs.tritondatacenter.com/cloudapi/#GetDatacenter) returns a 302 redirect to the CloudAPI endpoint of that datacenter, this doesn't seem to have any utility for a CLI tool, especially considering that [ListServices](https://apidocs.tritondatacenter.com/cloudapi/#ListServices) already exists and is expressed as `triton services`.

That being the case, I'm going to close this issue and the accompanying PR (#269).
